FROM python:3.10-slim

WORKDIR /frontend

COPY ./frontend/requirements.txt /frontend/requirements.txt
RUN pip install -r requirements.txt

COPY ./frontend/streamlit_app /frontend/streamlit_app

CMD ["streamlit", "run", "streamlit_app/main.py", "--server.port=5000", "--server.address=0.0.0.0"]
