services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./mlruns:/app/mlruns  # ✅ persist logs

  frontend:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend

  mlflow:
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns --default-artifact-root /mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
